name: detect-push-workflow
run-name: ${{ github.actor }} is learning github actions
on: [push]
jobs: 
  chech-bats-version:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: echo "push happened in repo"
  run_build_script:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: ./.github/scripts/build.sh
        shell: bash